language: cpp

matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9

    - os: linux
      dist: precise
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5

    - os: linux
      dist: precise
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'libstdc++-4.9-dev']
      env:
        - COMPILER=clang++-3.9

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER=clang++

    - os: osx
      osx_image: xcode9
      compiler: clang
      env:
        - COMPILER=clang++

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libsdl1.2-dev; fi
  - make -e CXX=$COMPILER -f Makefile.travis
